safe: false

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - simia-tech*.iml

gems:
  - jekyll-slim
  - jekyll-sass

sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed
